#!/bin/sh

gcc -DHAVE_CONFIG_H -I. -g -O2 -MT gbacklight.o -MD -MP -MF ".deps/gbacklight.Tpo" `pkg-config --cflags gtk+-2.0` -c -o gbacklight.o gbacklight.c
gcc -g -O2 -o gbacklight gbacklight.o -lXrandr -lXrender -lX11 `pkg-config --libs gtk+-2.0`

